version: '3'

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-test}'
      POSTGRES_USER: '${POSTGRES_USER:-test}'
    ports:
      - '5432:5432'
