name: Semantic release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GPR_TOKEN }}

      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install deps in quiet mode
        shell: bash
        run: npm ci -q

      - name: Release a new version
        run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GPR_TOKEN }}
